name = "career-launchpad"
compatibility_date = "2024-10-27"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

# Workers configuration
[build]
command = "npx @cloudflare/next-on-pages@1"

[build.environment_variables]
NODE_VERSION = "20"
